### PR TITLE
WIP: Support JSON for copy_table_to_redshift

### PR DESCRIPTION
**Pull request by jklukas**
Leaving as WIP until I get a test written. I'm not sure how to get postgres tests up and running, though. Does @wrobstory have advice about running the tests that require postgres?

### CODE REVIEW

**Comment by jklukas** [comment]
This PR also adds an optional delete_statement. This allows you to define a backfill where you eliminate existing records in the same transaction with loading the backfill.

**Comment by wrobstory** [comment]
This looks good so far- is there a reason you want to default to JSON rather than CSV? 

I have it on good authority from Python Wizard @jiffyclub that https://github.com/tk0miya/testing.postgresql is definitely the way to go for testing Postgres. Not 100% how it works with TravisCI.

**Comment by jklukas** [comment]
> is there a reason you want to default to JSON rather than CSV

CSV export has proven fragile. There are cases where we've chosen to omit a column on the Redshift side, for example, and the CSV export breaks due to the column mismatch. Or the Redshift table contains some old columns that have been dropped on the Postgres side. In both of those cases, we want the extra fields to be ignored, and JSON-based export allows that to happen naturally.

**Comment by jklukas** [comment]
Do we have docs about running the existing postgres tests manually?

**Comment by wrobstory** [comment]
No, I believe its `pytest -m postgrestest`

**Pull request merged**
