### PR TITLE
Fixing unicode string handling in CSV chunking

### PR DESCRIPTION
**Pull request by xstevens**

### CODE REVIEW

**Comment by wrobstory** [comment]
I'm surprised you need to use `codecs`. What's the failure case that caused this to happen?

**Comment by xstevens** [comment]
One of the "ascii codec can't encode character" errors. I don't have the exact message handy, but its because of our environment running Python 2.7.

**Comment by alialliallie** [comment]
@xstevens I think if you rebase this it'll fix up the CI checks from work I did, ran into this so +1 to merge after that

**Comment by alialliallie** [comment]
This was included in #16

**Pull request closed without merging**
